apiVersion: v1
kind: Service
metadata:
  name: go-app
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: go-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - image: nginx:latest
        name: go-app
        ports:
        - containerPort: 80
